name: official_site
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter:
  http:
  hooks_riverpod:
  flutter_hooks:
  freezed_annotation:
  json_annotation:
  json_serializable:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:

flutter:
  uses-material-design: true
